[package]
name = "password-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
rand = "0.8.5"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"